# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fh6UxMSQ5U5xxX8NLNhixI97ogYuUNCm

#Basic Python

##1.Split this string
"""

s = "Hi there sam!"

print(s.split())

"""##2.Use .format() to print the following string.

##Out should be: The diameter of Each is 12742 kilometers
"""

planet = "Earth"

diameter = 12742

print("The diameter of {} is {} kilometers".format(planet,diameter))

"""##3.In this nest dictionary grap the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

print(d['k1'][3]['tricky'][3]['target'][3])

"""#NUMPY"""

import numpy as np

"""##4.1 Create an array of 10 zeros?

##4.2 Create an array of 10 fives?
"""

np.zeros(10)

np.ones(10)*5

"""##5. create an array of all the even integers from 20 to 35"""

np.array([int(i) for i in range(20,35,2)])

"""##6. Create a 3x3 matrix with values ranging from 0 to 8"""

np.arange(0, 9).reshape(3,3)

"""##7. Concatenate a and b

##a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

np.concatenate((np.array([1,2,3]),np.array([4,5,6])))

"""#Pandas

##8. Create a data frame with 3 rows and 2 colums
"""

import pandas as pd

pd.DataFrame({0:[1]*3,1:[1]*3})

"""#9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

pd.date_range(start="01/01/2023",end="10/02/2023")

"""##10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

pd.DataFrame(lists)